In [65]:
import pandas as pd
import numpy as np
import re

Question 1- Write a Python program to replace all occurrences of a space, comma, or dot with a colon.
Sample Text- 'Python Exercises, PHP exercises.'
Expected Output: Python:Exercises::PHP:exercises:

In [66]:
pattern="[,. ]"
Sample_text='Python Exercises, PHP exercises.'
match= re.sub(pattern,":",Sample_text)
print(match)

Python:Exercises::PHP:exercises:

Question 2:-Create a dataframe using the dictionary below and remove everything (commas (,), !, XXXX, ;, etc.) from the columns except words.
Dictionary- {'SUMMARY' : ['hello, world!', 'XXXXX test', '123four, five:; six...']}
Expected output-
0      hello world
1             test
2    four five six

In [67]:
dictionary={'SUMMARY' : ['hello, world!', 'XXXXX test', '123four, five:; six...']}
df=pd.DataFrame(dictionary)
#print(df)
pattern='[\d.:;X!]+'
df['Replace']=df['SUMMARY'].str.replace(pattern,"",regex=True)
df['Replace']

0      hello, world
1              test
2    four, five six
Name: Replace, dtype: object

Question 3- Create a function in python to find all words that are at least 4 characters long in a string. The use of the re.compile() method is mandatory.

In [68]:
Text="I am Lalit and i am learning Data Science Course From DataTrained. and this is sample Text"
def find(text):
    pattern=re.compile(r'\b\w{4,}\b')
    match=pattern.findall(text)
    return match

Final_text=find(Text)
print(Final_text)

['Lalit', 'learning', 'Data', 'Science', 'Course', 'From', 'DataTrained', 'this', 'sample', 'Text']

Question 4- Create a function in python to find all three, four, and five character words in a string. The use of the re.compile() method is mandatory.

In [69]:
Text="I am Lalit and i am learning Data Science Course From DataTrained. and this is sample Text"
def find(text):
    pattern=re.compile(r'\b[a-zA-Z]{3,5}\b')
    match=pattern.findall(text)
    return match

Final_text=find(Text)
print(Final_text)

['Lalit', 'and', 'Data', 'From', 'and', 'this', 'Text']

Question 5- Create a function in Python to remove the parenthesis in a list of strings. The use of the re.compile() method is mandatory

In [70]:
string= [' "Hey(How)", "Are(You)" , "I am (Good)" ']
def remove(x):
    pattern=re.compile(r'\([^)]*\)')
    return [re.sub(pattern, '', s) for s in x]
match=remove(string)
print(match)

[' "Hey", "Are" , "I am " ']

Question 6- Write a python program to remove the parenthesis area from the text stored in the text file using Regular Expression.
Sample Text: ["example (.com)", "hr@fliprobo (.com)", "github (.com)", "Hello (Data Science World)", "Data (Scientist)"]
Expected Output: ["example", "hr@fliprobo", "github", "Hello", "Data"]

In [71]:
with open('example.txt','w') as file:
    file.write('"example (.com)", "hr@fliprobo (.com)", "github (.com)", "Hello (Data Science World)", "Data (Scientist)"')

with open('example.txt','r') as file:
    Read=file.read()

match=re.sub(r"\s*\([^)]*\)",'',Read)
print(match)

"example", "hr@fliprobo", "github", "Hello", "Data"

Question 7- Write a regular expression in Python to split a string into uppercase letters.
Sample text: “ImportanceOfRegularExpressionsInPython”
Expected Output: [‘Importance’, ‘Of’, ‘Regular’, ‘Expression’, ‘In’, ‘Python’]

In [72]:
pattern='[A-Z][^A-Z]*'
sample_text='ImportanceOfRegularExpressionsInPython'
match=re.findall(pattern,sample_text)
print(match)

['Importance', 'Of', 'Regular', 'Expressions', 'In', 'Python']

Question 8- Create a function in python to insert spaces between words starting with numbers.
Sample Text: “RegularExpression1IsAn2ImportantTopic3InPython"
Expected Output: RegularExpression 1IsAn 2ImportantTopic 3InPython

In [73]:
sample="RegularExpression1IsAn2ImportantTopic3InPython"
def space(sample):
    pattern='(\d)([A-Z])'
    final=re.sub(pattern,r' \1\2',sample)
    return final

final_result=space(sample)
print(final_result)

RegularExpression 1IsAn 2ImportantTopic 3InPython

Question 9- Create a function in python to insert spaces between words starting with capital letters or with numbers.
Sample Text: “RegularExpression1IsAn2ImportantTopic3InPython"
Expected Output:  RegularExpression 1 IsAn 2 ImportantTopic 3 InPython

In [74]:
sample="RegularExpression1IsAn2ImportantTopic3InPython"
def space(sample):
    pattern='(\d)([A-Z])'
    final=re.sub(pattern,r' \1 \2',sample)
    return final

final_result=space(sample)
print(final_result)

RegularExpression 1 IsAn 2 ImportantTopic 3 InPython

Question 10- Use the github link below to read the data and create a dataframe. After creating the dataframe extract the first 6 letters of each country and store in the dataframe under a new column called first_five_letters.
Github Link-  https://raw.githubusercontent.com/dsrscientist/DSData/master/happiness_score_dataset.csv

In [75]:
df=pd.read_csv('https://raw.githubusercontent.com/dsrscientist/DSData/master/happiness_score_dataset.csv')

In [76]:
df.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [77]:
df['First_Five_Letter'] = df['Country'].str[:6]

In [78]:
df.sample(5)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,First_Five_Letter
37,Taiwan,Eastern Asia,38,6.298,0.03868,1.29098,1.07617,0.87530,0.39740,0.08129,0.25376,2.32323,Taiwan
126,Armenia,Central and Eastern Europe,127,4.350,0.04763,0.76821,0.77711,0.72990,0.19847,0.03900,0.07855,1.75873,Armeni
10,Israel,Middle East and Northern Africa,11,7.278,0.03470,1.22857,1.22393,0.91387,0.41319,0.07785,0.33172,3.08854,Israel
64,Jamaica,Latin America and Caribbean,65,5.709,0.13693,0.81038,1.15102,0.68741,0.50442,0.02299,0.21230,2.32038,Jamaic
125,Djibouti,Sub-Saharan Africa,126,4.369,0.08096,0.44025,0.59207,0.36291,0.46074,0.28105,0.18093,2.05125,Djibou

Question 11- Write a Python program to match a string that contains only upper and lowercase letters, numbers, and underscores.

In [79]:
Sample="IAMlalit_2023"
pattern = '^[0-9_A-Za-z]+$'
if re.match(pattern,Sample):
    print('Matches')
else:
    print('Not Matches')

Matches

Question 12- Write a Python program where a string will start with a specific number.

In [80]:
number1= '20233'
number2= '92554'
def match(string):
    if re.match(r'^2',string):
        print('String Matches Number Succesfully')
    else:
        print('String not Matches')
Result=match('number1')
print(Result)

String not Matches
None

Question 13- Write a Python program to remove leading zeros from an IP address

In [100]:
IP = "92.158.01.08"
match = re.sub('\.[0]*', '.',IP)
print(match)

92.158.1.8

Question 14- Write a regular expression in python to match a date string in the form of Month name followed by day number and year stored in a text file.
Sample text :  ' On August 15th 1947 that India was declared independent from British colonialism, and the reins of control were handed over to the leaders of the Country’.
Expected Output- August 15th 1947

In [82]:
with open('Testing.txt', 'r') as file:
    text=file.read()

pattern=(r'\b(?:August) \d{1,2}(?:th) \d{4}\b')
match=re.findall(pattern,text)
print(match)

['August 15th 1947']

Question 15- Write a Python program to search some literals strings in a string. 
Sample text :'The quick brown fox jumps over the lazy dog.'
Searched words : 'fox', 'dog', 'horse'

In [83]:
pattern=["fox","dog","horse"]
text="The quick brown fox jumps over the lazy dog."
for x in pattern:
    print(x,text)
    if re.search(x,text):
        print("Matched")
    else:
        print("Not Matched")

fox The quick brown fox jumps over the lazy dog.
Matched
dog The quick brown fox jumps over the lazy dog.
Matched
horse The quick brown fox jumps over the lazy dog.
Not Matched

Question 16- Write a Python program to search a literals string in a string and also find the location within the original string where the pattern occurs
Sample text : 'The quick brown fox jumps over the lazy dog.'
Searched words : 'fox'

In [84]:
sample='The quick brown fox jumps over the lazy dog.'
pattern="fox"
result=re.search(pattern,sample)
location=sample.find('fox')
print(result)
print(location)

<re.Match object; span=(16, 19), match='fox'>
16

Question 17- Write a Python program to find the substrings within a string.
Sample text : 'Python exercises, PHP exercises, C# exercises'
Pattern : 'exercises'.

In [85]:
Sample_text="Python exercises, PHP exercises, C# exercises"
pattern='exercises'
for x in re.findall(pattern,Sample_text):
    print(x)

exercises
exercises
exercises

Question 18- Write a Python program to find the occurrence and position of the substrings within a string.

In [86]:
Sample_text=[ "Python exercises", "PHP exercises", "C# exercises"]
pattern='exercises'
for x in Sample_text:
    search=re.search(pattern,x)
    print(search)

<re.Match object; span=(7, 16), match='exercises'>
<re.Match object; span=(4, 13), match='exercises'>
<re.Match object; span=(3, 12), match='exercises'>

Question 19- Write a Python program to convert a date of yyyy-mm-dd format to dd-mm-yyyy format.

In [87]:
Date='2024-02-15'
pattern=r'(\d{4})-(\d{1,2})-(\d{1,2})'
change= re.sub(pattern,'\\3-\\2-\\1',Date)
print(change)

15-02-2024

Question 20- Create a function in python to find all decimal numbers with a precision of 1 or 2 in a string. The use of the re.compile() method is mandatory.
Sample Text: "01.12 0132.123 2.31875 145.8 3.01 27.25 0.25"
Expected Output: ['01.12', '145.8', '3.01', '27.25', '0.25']

In [88]:
Sample_text="01.12 0132.123 2.31875 145.8 3.01 27.25 0.25"
pattern=re.compile(r'\b\d+\.\d{1,2}\b')
match=re.findall(pattern,Sample_text)
print(match)

['01.12', '145.8', '3.01', '27.25', '0.25']

Question 21- Write a Python program to separate and print the numbers and their position of a given string.

In [89]:
sample=" Hey i have 100 Rs Note "
for x in re.finditer(r'\d+',sample):
    print(x)
    print('Number:-',x.group(0))
    print("Position of given string:-", x.start())

<re.Match object; span=(12, 15), match='100'>
Number:- 100
Position of given string:- 12

Question 22- Write a regular expression in python program to extract maximum/largest numeric value from a string.
Sample Text:  'My marks in each semester are: 947, 896, 926, 524, 734, 950, 642'
Expected Output: 950

In [90]:
sample_text="My marks in each semester are: 947, 896, 926, 524, 734, 950, 642"
match=re.findall(r'\d+',sample_text)
maximum=max(match)
print(maximum)

950

Question 23- Create a function in python to insert spaces between words starting with capital letters.
Sample Text: “RegularExpressionIsAnImportantTopicInPython"
Expected Output: Regular Expression Is An Important Topic In Python

In [91]:
Text="RegularExpressionIsAnImportantTopicInPython"

def add_space(text):
    pattern=r'([A-Z][a-z]+)'
    match=re.sub(pattern,r' \1',text)
    return match

result= add_space(Text)
print(result)

 Regular Expression Is An Important Topic In Python

Question 24- Python regex to find sequences of one upper case letter followed by lower case letters

In [92]:
def check(x):
    pattern=r'[A-Z][a-z]+$'
    if re.search(pattern,x):
        print("It's a Match")
    else:
        print("Not a Match")

print(check("King"))

It's a Match
None

Question 25- Write a Python program to remove continuous duplicate words from Sentence using Regular Expression.
Sample Text: "Hello hello world world"
Expected Output: Hello hello world

In [93]:
sample_text="Hello hello world world"
pattern=r'\b(\w+)(?:\W+\1\b)+'
match=re.sub(pattern,r'\1',sample_text)
print(match)

Hello hello world

Question 26-  Write a python program using RegEx to accept string ending with alphanumeric character.

In [94]:
def Check(x):
    pattern=r'\w$'
    if re.search(pattern,x):
        print('Accepted')
        
    else:
        print("Not Accepted")
        
        
result=Check('Hey i am Lalit0')

Accepted

Question 27-Write a python program using RegEx to extract the hashtags.
Sample Text:  """RT @kapil_kausik: #Doltiwal I mean #xyzabc is "hurt" by #Demonetization as the same has rendered USELESS <ed><U+00A0><U+00BD><ed><U+00B1><U+0089> "acquired funds" No wo"""
Expected Output: ['#Doltiwal', '#xyzabc', '#Demonetization'

In [95]:
sample="""RT @kapil_kausik: #Doltiwal I mean #xyzabc is "hurt" by #Demonetization as the same has rendered USELESS <ed><U+00A0><U+00BD><ed><U+00B1><U+0089> "acquired funds" No wo"""
pattern=r'#\w+'
match=re.findall(pattern,sample)
print(match)

['#Doltiwal', '#xyzabc', '#Demonetization']

Question 28- Write a python program using RegEx to remove <U+..> like symbols
Check the below sample text, there are strange symbols something of the sort <U+..> all over the place. You need to come up with a general Regex expression that will cover all such symbols.
Sample Text: "@Jags123456 Bharat band on 28??<ed><U+00A0><U+00BD><ed><U+00B8><U+0082>Those who  are protesting #demonetization  are all different party leaders"
Expected Output: @Jags123456 Bharat band on 28??<ed><ed>Those who  are protesting #demonetization  are all different party leaders

In [96]:
sample="@Jags123456 Bharat band on 28??<ed><U+00A0><U+00BD><ed><U+00B8><U+0082>Those who  are protesting #demonetization  are all different party leaders"
pattern=r"<U\+\w{4}>"
match=re.sub(pattern,'',sample)
print(match)

@Jags123456 Bharat band on 28??<ed><ed>Those who  are protesting #demonetization  are all different party leaders

Question 29- Write a python program to extract dates from the text stored in the text file.
Sample Text: Ron was born on 12-09-1992 and he was admitted to school 15-12-1999.
Note- Store this sample text in the file and then extract dates

In [97]:
with open('sample.txt','w') as file:
    file.write("Ron was born on 12-09-1992 and he was admitted to school 15-12-1999.")

with open('sample.txt','r') as file:
    Text=file.read()

date=r'\d{2}-\d{2}-\d{4}'
result=re.findall(date,Text)
print(result)

['12-09-1992', '15-12-1999']

Question 30- Create a function in python to remove all words from a string of length between 2 and 4.
The use of the re.compile() method is mandatory.
Sample Text: "The following example creates an ArrayList with a capacity of 50 elements. 4 elements are then added to the ArrayList and the ArrayList is trimmed accordingly."
Expected Output:  following example creates ArrayList a capacity elements. 4 elements added ArrayList ArrayList trimmed accordingly.

In [98]:
sample_text="The following example creates an ArrayList with a capacity of 50 elements. 4 elements are then added to the ArrayList and the ArrayList is trimmed accordingly."
pattern=re.compile(r'\b\w{2,4}\b')
match=re.sub(pattern,'',sample_text)
print(match)

 following example creates  ArrayList  a capacity   elements. 4 elements   added   ArrayList   ArrayList  trimmed accordingly.