In [2]:
pip --version

pip 24.2 from C:\Users\DELL\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip (python 3.11)

Note: you may need to restart the kernel to use updated packages.

In [1]:
!pip install selenium

Collecting selenium
  Downloading selenium-4.24.0-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.0.4)
Collecting trio~=0.17 (from selenium)
  Downloading trio-0.26.2-py3-none-any.whl.metadata (8.6 kB)
Collecting trio-websocket~=0.9 (from selenium)
  Downloading trio_websocket-0.11.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from selenium) (2023.7.22)
Collecting typing_extensions~=4.9 (from selenium)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting websocket-client~=1.8 (from selenium)
  Downloading websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
Collecting attrs>=23.2.0 (from trio~=0.17->selenium)
  Downloading attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting sortedcontainers (from trio~=0.17->selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from trio~=0.17->selenium) (3.4)
Collecting outcome (from trio~=0.17->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium)
  Downloading wsproto-1.2.0-py3-none-any.whl.metadata (5.6 kB)
Collecting pysocks!=1.5.7,<2.0,>=1.5.6 (from urllib3[socks]<3,>=1.26->selenium)
  Downloading PySocks-1.7.1-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: pycparser in c:\users\dell\appdata\local\programs\python\python311\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Collecting h11<1,>=0.9.0 (from wsproto>=0.14->trio-websocket~=0.9->selenium)
  Downloading h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Downloading selenium-4.24.0-py3-none-any.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.6 MB 8.4 MB/s eta 0:00:02
   ------------ --------------------------- 2.9/9.6 MB 8.4 MB/s eta 0:00:01
   --------------- ------------------------ 3.7/9.6 MB 7.3 MB/s eta 0:00:01
   --------------------- ------------------ 5.2/9.6 MB 6.8 MB/s eta 0:00:01
   --------------------------- ------------ 6.6/9.6 MB 6.5 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.6 MB 6.7 MB/s eta 0:00:01
   -------------------------------------- - 9.2/9.6 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 6.2 MB/s eta 0:00:00
Downloading trio-0.26.2-py3-none-any.whl (475 kB)
Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading websocket_client-1.8.0-py3-none-any.whl (58 kB)
Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Downloading h11-0.14.0-py3-none-any.whl (58 kB)
Installing collected packages: sortedcontainers, websocket-client, typing_extensions, pysocks, h11, attrs, wsproto, outcome, trio, trio-websocket, selenium
  Attempting uninstall: websocket-client
    Found existing installation: websocket-client 1.6.2
    Uninstalling websocket-client-1.6.2:
      Successfully uninstalled websocket-client-1.6.2
  Attempting uninstall: attrs
    Found existing installation: attrs 23.1.0
    Uninstalling attrs-23.1.0:
      Successfully uninstalled attrs-23.1.0
Successfully installed attrs-24.2.0 h11-0.14.0 outcome-1.3.0.post0 pysocks-1.7.1 selenium-4.24.0 sortedcontainers-2.4.0 trio-0.26.2 trio-websocket-0.11.1 typing_extensions-4.12.2 websocket-client-1.8.0 wsproto-1.2.0

Q1: In this question you have to scrape data using the filters available on the webpage You have to use the location and 
salary filter. 
You have to scrape data for “Data Scientist” designation for first 10 job results. 
You have to scrape the job-title, job-location, company name, experience required. 
The location filter to be used is “Delhi/NCR”. The salary filter to be used is “3-6” lakhs 
The task will be done as shown in the below steps: 
1. first get the web page https://www.naukri.com/
2. Enter “Data Scientist” in “Skill, Designations, and Companies” field. 
3. Then click the search button. 
4. Then apply the location filter and salary filter by checking the respective boxes 
5. Then scrape the data for the first 10 jobs results you get. 
6. Finally create a dataframe of the scraped data.

In [2]:
import selenium
import pandas as pd 
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [3]:
driver=webdriver.Chrome()

In [4]:
#opening the page
driver.get('https://www.naukri.com/')

In [4]:
#To write Data Scientist in search field
desigination=driver.find_element(By.CLASS_NAME,"suggestor-input ")
desigination.send_keys('Data Scientist')

In [5]:
#to click on search
search=driver.find_element(By.CLASS_NAME,'qsbSubmit')
search.click()

In [7]:
#to markdown boxes
salary=driver.find_element(By.XPATH,'/html/body/div/div/main/div[1]/div[1]/div/div/div[2]/div[4]/div[2]/div[3]/label/i')
salary.click()

In [8]:
location=driver.find_element(By.XPATH,'/html/body/div/div/main/div[1]/div[1]/div/div/div[2]/div[5]/div[2]/div[2]/label/i')
location.click()

In [9]:
job_title=[]
company_name=[]
Experience=[]
location=[]

In [10]:

#to scrap the details of the job

title_tags=driver.find_elements(By.XPATH,'//a[@class="title "]')
for i in title_tags[0:10]:
    title=i.text
    job_title.append(title)

company_tags=driver.find_elements(By.XPATH,'//a[@class=" comp-name mw-25"]')
for i in company_tags[0:10]:
    name=i.text
    company_name.append(name)

exp_tags=driver.find_elements(By.XPATH,'//span[@class="expwdth"]')
for i in exp_tags[0:10]:
    exp=i.text
    Experience.append(exp)

location_tags=driver.find_elements(By.XPATH,'//span[@class="ni-job-tuple-icon ni-job-tuple-icon-srp-location loc"]')
for i in location_tags[0:10]:
    loc=i.text
    location.append(loc)

In [11]:
print(len(job_title),len(company_name),len(Experience),len(location))

10 10 10 10

In [12]:
#creating The DataFrame 
df=pd.DataFrame({'Job_Title':job_title,'Company':company_name,'Experience_Required':Experience,'Location':location})
df

,Job_Title,Company,Experience_Required,Location
0,Data Scientist,Nityo Infotech,3-7 Yrs,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C..."
1,Data Scientist: Artificial Intelligence,IBM,3-7 Yrs,Gurugram
2,Data Scientist (AI/ML)|| US Based MNC || Noida,Collegedunia,3-5 Yrs,Hybrid - Noida
3,Data Analyst,Growthjockey,0-2 Yrs,Gurugram
4,Snowflake Data Engineer,Essenware,0-5 Yrs,New Delhi
5,,Biz Tech Consultants,0-1 Yrs,Gurugram
6,,Biz Tech Consultants,2-5 Yrs,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C..."
7,,Biz Tech Consultants,2-6 Yrs,"Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C..."
8,Data Scientist,PayU,3-8 Yrs,Gurugram
9,Data Scientist,Innovaccer,3-8 Yrs,Ghaziabad

Q2: Write a python program to scrape data for “Data Scientist” Job position in “Bangalore” location. You have to scrape the 
job-title, job-location, company_name, experience_required. You have to scrape first 10 jobs data.
This task will be done in following steps:
1. First get the webpage https://www.shine.com/
2. Enter “Data Analyst” in “Job title, Skills” field and enter “Bangalore” in “enter the location” field.
3. Then click the searchbutton. 
4. Then scrape the data for the first 10 jobs results you get. 
5. Finally create a dataframe of the scraped data. ews.

In [5]:
driver=webdriver.Chrome()

In [8]:
driver.get('https://www.shine.com/')

In [11]:
Enter_job=driver.find_element(By.XPATH,'/html/body/div/div[4]/div/div[2]/div[2]/div/form/div/div[1]/ul/li[1]/div/input')
Enter_job.send_keys('Data Analyst')

In [13]:
Enter_loc=driver.find_element(By.XPATH,'/html/body/div/div[4]/div/div[2]/div[2]/div/form/div/div[1]/ul/li[2]/div/input')
Enter_loc.send_keys('Bangalore')

In [28]:
Enter=driver.find_element(By.XPATH,'/html/body/div/div[4]/div/div[2]/div[2]/div/form/div/div[2]/div/button')
Enter.click()

In [14]:
job_Title=[]
job_location=[]
comp_name=[]
exp_req=[]

In [15]:
title=driver.find_elements(By.XPATH,'//strong[@class="jobCard_pReplaceH2__xWmHg"]')
for i in title[0:10]:
    titles=i.text
    job_Title.append(titles)

locations=driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_lists_item__YxRkV jobCard_locationIcon__zrWt2"]')
for i in locations[0:10]:
    locs=i.text
    job_location.append(locs)

names=driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_cName__mYnow"]')
for i in names[0:10]:
    name=i.text
    comp_name.append(name)

experience=driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_jobIcon__3FB1t"]')
for i in experience[0:10]:
    expe=i.text
    exp_req.append(expe)

In [16]:
print(len(job_Title),len(job_location),len(comp_name),len(exp_req))

10 10 10 10

In [17]:
data=pd.DataFrame({'Title':job_Title,'Location':job_location,'Company':comp_name,'Experience_Required':exp_req})
data

,Title,Location,Company,Experience_Required
0,Social Media Specialist1,Bangalore\n+4,sunil kumar,0 to 4 Yrs
1,Data Entry Senior Representative,Bilaspur\n+9,v-tech data outsourcing,0 to 1 Yr
2,Data Entry Executive,Tambaram\n+9,v-tech data outsourcing,0 to 1 Yr
3,Relationship Trainee,Bangalore,team hr gsa private limited,0 to 1 Yr
4,Urgent Looking for SQL Developer,Mohali\n+1,rts systems private limited,4 to 6 Yrs
5,Data Operator,Bangalore\n+9,v-tech data outsourcing,0 to 1 Yr
6,Mega Drive at Aditya Birla Sun Life Insurance ...,Mumbai City,aditya birla sun life insurance com...,1 to 6 Yrs
7,Sales Associate,Hyderabad\n+2,flexi ventures pvt. ltd.,1 to 3 Yrs
8,Senior Executive,Kolkata,hdfc ergo general insurance company...,0 to 3 Yrs
9,Unit Sales Manager,Patiala,icici lombard general insurance co....,0 to 4 Yrs

Q3: Scrape 100 reviews data from flipkart.com for iphone11 phone. You have to go the link: 
https://www.flipkart.com/apple-iphone-11-black-64-gb/productreviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&marketplace=F
LIPKART

As shown in the above page you have to scrape the tick marked attributes. These are:
1. Rating
2. Review summary
3. Full review
4. You have to scrape this data for first 100reviews

In [3]:
driver=webdriver.Chrome()

In [4]:
driver.get('https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&marketplace=FLIPKART')
time.sleep(2)

In [5]:
rating=[]
review_sum=[]
full_review=[]

In [6]:

rate=driver.find_elements(By.XPATH,'//div[@class="XQDdHH Ga3i8K"]')
for i in rate:
    ra=i.text
    rating.append(ra)

reviu=driver.find_elements(By.XPATH,'//p[@class="z9E0IG"]')
for i in reviu:
    vie= i.text
    review_sum.append(vie)

full=driver.find_elements(By.XPATH,'//div[@class="ZmyHeo"]')
for i in full:
    ful=i.text
    full_review.append(ful)

        
        
next_btn=driver.find_element(By.CLASS_NAME,"WSL9JP")
next_btn.click()

print(len(rating),len(review_sum),len(full_review))

10 10 10

In [7]:

rate=driver.find_elements(By.XPATH,'//div[@class="XQDdHH Ga3i8K"]')
for i in rate:
    ra=i.text
    rating.append(ra)

reviu=driver.find_elements(By.XPATH,'//p[@class="z9E0IG"]')
for i in reviu:
    vie= i.text
    review_sum.append(vie)

full=driver.find_elements(By.XPATH,'//div[@class="ZmyHeo"]')
for i in full:
    ful=i.text
    full_review.append(ful)

        
        
next_btn=driver.find_element(By.CLASS_NAME,"WSL9JP")
next_btn.click()

print(len(rating),len(review_sum),len(full_review))

20 20 20

In [7]:

rate=driver.find_elements(By.XPATH,'//div[@class="XQDdHH Ga3i8K"]')
for i in rate:
    ra=i.text
    rating.append(ra)

reviu=driver.find_elements(By.XPATH,'//p[@class="z9E0IG"]')
for i in reviu:
    vie= i.text
    review_sum.append(vie)

full=driver.find_elements(By.XPATH,'//div[@class="ZmyHeo"]')
for i in full:
    ful=i.text
    full_review.append(ful)

        
        
next_btn=driver.find_element(By.CLASS_NAME,"WSL9JP")
next_btn.click()

print(len(rating),len(review_sum),len(full_review))

20 20 20

In [9]:

rate=driver.find_elements(By.XPATH,'//div[@class="XQDdHH Ga3i8K"]')
for i in rate:
    ra=i.text
    rating.append(ra)

reviu=driver.find_elements(By.XPATH,'//p[@class="z9E0IG"]')
for i in reviu:
    vie= i.text
    review_sum.append(vie)

full=driver.find_elements(By.XPATH,'//div[@class="ZmyHeo"]')
for i in full:
    ful=i.text
    full_review.append(ful)

        
        
next_btn=driver.find_element(By.CLASS_NAME,"WSL9JP")
next_btn.click()

print(len(rating),len(review_sum),len(full_review))

40 40 40

In [8]:

rate=driver.find_elements(By.XPATH,'//div[@class="XQDdHH Ga3i8K"]')
for i in rate:
    ra=i.text
    rating.append(ra)

reviu=driver.find_elements(By.XPATH,'//p[@class="z9E0IG"]')
for i in reviu:
    vie= i.text
    review_sum.append(vie)

full=driver.find_elements(By.XPATH,'//div[@class="ZmyHeo"]')
for i in full:
    ful=i.text
    full_review.append(ful)

        
        
next_btn=driver.find_element(By.CLASS_NAME,"WSL9JP")
next_btn.click()

print(len(rating),len(review_sum),len(full_review))

30 30 30

In [11]:

rate=driver.find_elements(By.XPATH,'//div[@class="XQDdHH Ga3i8K"]')
for i in rate:
    ra=i.text
    rating.append(ra)

reviu=driver.find_elements(By.XPATH,'//p[@class="z9E0IG"]')
for i in reviu:
    vie= i.text
    review_sum.append(vie)

full=driver.find_elements(By.XPATH,'//div[@class="ZmyHeo"]')
for i in full:
    ful=i.text
    full_review.append(ful)

        
        
next_btn=driver.find_element(By.CLASS_NAME,"WSL9JP")
next_btn.click()

print(len(rating),len(review_sum),len(full_review))

60 60 60

In [9]:

rate=driver.find_elements(By.XPATH,'//div[@class="XQDdHH Ga3i8K"]')
for i in rate:
    ra=i.text
    rating.append(ra)

reviu=driver.find_elements(By.XPATH,'//p[@class="z9E0IG"]')
for i in reviu:
    vie= i.text
    review_sum.append(vie)

full=driver.find_elements(By.XPATH,'//div[@class="ZmyHeo"]')
for i in full:
    ful=i.text
    full_review.append(ful)

        
        
next_btn=driver.find_element(By.CLASS_NAME,"WSL9JP")
next_btn.click()

print(len(rating),len(review_sum),len(full_review))

40 40 40

In [13]:

rate=driver.find_elements(By.XPATH,'//div[@class="XQDdHH Ga3i8K"]')
for i in rate:
    ra=i.text
    rating.append(ra)

reviu=driver.find_elements(By.XPATH,'//p[@class="z9E0IG"]')
for i in reviu:
    vie= i.text
    review_sum.append(vie)

full=driver.find_elements(By.XPATH,'//div[@class="ZmyHeo"]')
for i in full:
    ful=i.text
    full_review.append(ful)

        
        
next_btn=driver.find_element(By.CLASS_NAME,"WSL9JP")
next_btn.click()

print(len(rating),len(review_sum),len(full_review))

80 80 80

In [ ]:

rate=driver.find_elements(By.XPATH,'//div[@class="XQDdHH Ga3i8K"]')
for i in rate:
    ra=i.text
    rating.append(ra)

reviu=driver.find_elements(By.XPATH,'//p[@class="z9E0IG"]')
for i in reviu:
    vie= i.text
    review_sum.append(vie)

full=driver.find_elements(By.XPATH,'//div[@class="ZmyHeo"]')
for i in full:
    ful=i.text
    full_review.append(ful)

        
        
next_btn=driver.find_element(By.CLASS_NAME,"WSL9JP")
next_btn.click()

print(len(rating),len(review_sum),len(full_review))

In [18]:

rate=driver.find_elements(By.XPATH,'//div[@class="XQDdHH Ga3i8K"]')
for i in rate:
    ra=i.text
    rating.append(ra)

reviu=driver.find_elements(By.XPATH,'//p[@class="z9E0IG"]')
for i in reviu:
    vie= i.text
    review_sum.append(vie)

full=driver.find_elements(By.XPATH,'//div[@class="ZmyHeo"]')
for i in full:
    ful=i.text
    full_review.append(ful)

        
        
next_btn=driver.find_element(By.CLASS_NAME,"WSL9JP")
next_btn.click()

print(len(rating),len(review_sum),len(full_review))

110 110 110

In [17]:
df=pd.DataFrame({'Rating':rating,'Review Summary':review_sum,'Full Review':full_review})
df

,Rating,Review Summary,Full Review
0,5,<selenium.webdriver.remote.webelement.WebEleme...,Very very good
1,5,<selenium.webdriver.remote.webelement.WebEleme...,Good Camera
2,5,<selenium.webdriver.remote.webelement.WebEleme...,Camera is awesome\nBest battery backup\nA perf...
3,5,<selenium.webdriver.remote.webelement.WebEleme...,Feeling awesome after getting the delivery of ...
4,5,<selenium.webdriver.remote.webelement.WebEleme...,Value for money 😍
...,...,...,...
95,5,<selenium.webdriver.remote.webelement.WebEleme...,Best camera ever
96,5,<selenium.webdriver.remote.webelement.WebEleme...,Gifted my man on his 30th birthday 🎂 He loves ...
97,5,<selenium.webdriver.remote.webelement.WebEleme...,Finally got it 😙
98,5,<selenium.webdriver.remote.webelement.WebEleme...,Value for money❤️❤️\nIts awesome mobile phone ...
99,4,<selenium.webdriver.remote.webelement.WebEleme...,I was using Iphone 6s and also Oneplus 6t. Bot...

Q4: Scrape data forfirst 100 sneakers you find whenyouvisitflipkart.com and search for “sneakers” inthe search
field.
You have to scrape 3 attributes of each sneaker:
1. Brand
2. ProductDescription
3. Price
As shown in the below image, you have to scrape the above attributes

In [2]:
#to lauch the chrome 
driver=webdriver.Chrome()
driver.get('https://www.flipkart.com/')

In [3]:
#sending values to the search 
value=driver.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div/div/div[1]/div[1]/header/div[1]/div[2]/form/div/div/input')
value.send_keys('sneakers')

In [4]:
#to click on search
search_btn=driver.find_element(By.XPATH,'/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div/div/div[1]/div[1]/header/div[1]/div[2]/form/div/button')
search_btn.click()

In [6]:
#Creating the empty list to store the scrap values
brand=[]
descp=[]
price=[]

In [8]:
#creating loop to scrap all data 
Brand=driver.find_elements(By.XPATH,'//div[@class="syl9yP"]')
for i in Brand:
    comp=i.text
    brand.append(comp)
#we have to create two loops for the product description because their are two classes are prasent in page with product discriptionn
discription=driver.find_elements(By.XPATH,'//a[@class="WKTcLC BwBZTg"]')
for i in discription:
    discrip=i.text
    descp.append(discrip)
    
text=driver.find_elements(By.XPATH,'//a[@class="WKTcLC"]')
for i in text:
    discript=i.text
    descp.append(discript)

rate=driver.find_elements(By.XPATH,'//div[@class="Nx9bqj"]')
for i in rate:
    pri=i.text
    price.append(pri)

In [10]:
#to press on next button
next=driver.find_element(By.XPATH,'/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[11]/span')
next.click()

In [11]:
Brand=driver.find_elements(By.XPATH,'//div[@class="syl9yP"]')
for i in Brand:
    comp=i.text
    brand.append(comp)

discription=driver.find_elements(By.XPATH,'//a[@class="WKTcLC BwBZTg"]')
for i in discription:
    discrip=i.text
    descp.append(discrip)
    
text=driver.find_elements(By.XPATH,'//a[@class="WKTcLC"]')
for i in text:
    discript=i.text
    descp.append(discript)

rate=driver.find_elements(By.XPATH,'//div[@class="Nx9bqj"]')
for i in rate:
    pri=i.text
    price.append(pri)

In [14]:
next=driver.find_element(By.XPATH,'/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[12]/span')
next.click()

In [15]:
Brand=driver.find_elements(By.XPATH,'//div[@class="syl9yP"]')
for i in Brand[0:20]:
    comp=i.text
    brand.append(comp[0:20])
    
text=driver.find_elements(By.XPATH,'//a[@class="WKTcLC"]')
for i in text[0:20]:
    discript=i.text
    descp.append(discript[0:20])

rate=driver.find_elements(By.XPATH,'//div[@class="Nx9bqj"]')
for i in rate[0:20]:
    pri=i.text
    price.append(pri[0:20])

In [16]:
print(len(brand),len(descp),len(price))

100 100 100

In [17]:
#Creating a DataFrame 
df=pd.DataFrame({'Brand':brand,'Product Description':descp,'Price':price})

In [18]:
df

        Brand                               Product Description   Price
0       Sparx  SM 671 | Stylish, Comfortable | Sneakers For Men    ₹974
1    Vellinto           Casual Sneakrs For Men Sneakers For Men    ₹599
2       WROGN  SM 162 | Stylish, Comfortable | Sneakers For Men    ₹699
3      ADIDAS                       KLR-009 01 Sneakers For Men  ₹3,654
4    BERSACHE                                  Sneakers For Men    ₹658
..        ...                                               ...     ...
95   Skechers                                  Sneakers For Men  ₹3,150
96  RUN SEVEN                                  Sneakers For Men    ₹889
97     REEBOK                              Dynamite Lace-Up Sne  ₹4,399
98     CAMPUS                              ( by GO21 ) Soft Ins    ₹609
99   TWO SOFT                              Turin 3 Sneakers For    ₹499

[100 rows x 3 columns]

In [ ]:
Q5: Go to webpage https://www.amazon.in/ Enter “Laptop” in the search field and then click the search icon. Then set CPU
Type filter to “Intel Core i7” as shown in the below image:

Aftersetting the filters scrape first 10 laptops data. You have to scrape 3 attributes for each laptop:
1. Title
2. Ratings
3. Price

In [2]:
driver=webdriver.Chrome()
driver.get('https://www.amazon.in/')

In [3]:
input=driver.find_element(By.ID,"twotabsearchtextbox")
input.send_keys('Laptop')

In [4]:
search=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input')
search.click()

In [5]:
filter=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/div[1]/div[2]/div/div[3]/span/div[1]/span/div/div/div[5]/ul[2]/span/span[9]/li/span/a/div/label/i')
filter.click()

In [6]:
title=[]
rating=[]
price=[]

In [7]:
heading=driver.find_elements(By.XPATH,'//span[@class="a-size-medium a-color-base a-text-normal"]')
for i in heading[0:10]:
    head=i.text
    title.append(head[0:10])

In [8]:
amount=driver.find_elements(By.XPATH,'//span[@class="a-price-whole"]')
for i in amount[0:10]:
    money=i.text
    price.append(money[0:10])

In [9]:
rate=driver.find_elements(By.XPATH,'//span[@class="a-icon-alt"]')
for i in rate[0:10]:
    rates=i.text
    rating.append(rates[0:10])

In [10]:
print(len(title),len(price),len(rating))

10 10 10

In [12]:
df=pd.DataFrame({'Titles':title,'Ratings':rating,'Price':price})

In [13]:
df

       Titles Ratings   Price
0  HP Laptop           59,990
1  Dell [Smar          75,490
2  Acer Aspir          49,990
3  BKN® Mini              277
4  HP Pavilio          76,990
5  Acer ALG 1          71,990
6  ASUS Vivob          61,990
7  (Refurbish          27,531
8  Dell Inspi          69,890
9  MSI Thin 1          69,990

Q6: Write a python program to scrape data for Top 1000 Quotes of All Time.
The above task will be done in following steps:
1. First get the webpagehttps://www.azquotes.com/
2. Click on TopQuote
3. Than scrap a)Quote b) Author c) Type Of Quotes

In [2]:
#to send request to chrome and than click is use to click on top 100 quotes
driver=webdriver.Chrome()
driver.get('https://www.azquotes.com/')
press=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/div[1]/div/div[3]/ul/li[5]/a')
press.click()

In [3]:
quote=[]
author=[]
typs=[]

In [4]:
#to scrap the data and insert it in the empty list and to click on next page there is a next button below 
lines=driver.find_elements(By.XPATH,'//a[@class="title"]')
for i in lines:
    line=i.text
    quote.append(line)

auth=driver.find_elements(By.XPATH,'//div[@class="author"]')
for i in auth:
    writer=i.text
    author.append(writer)
    
typ=driver.find_elements(By.XPATH,'//div[@class="tags"]')
for i in typ:
    types=i.text
    typs.append(types)

next=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div/div/div/div[1]/div/div[4]/li[12]/a')
next.click()

print(len(quote),len(author),len(typs))

100 100 100

In [5]:
lines=driver.find_elements(By.XPATH,'//a[@class="title"]')
for i in lines:
    line=i.text
    quote.append(line)

auth=driver.find_elements(By.XPATH,'//div[@class="author"]')
for i in auth:
    writer=i.text
    author.append(writer)
    
typ=driver.find_elements(By.XPATH,'//div[@class="tags"]')
for i in typ:
    types=i.text
    typs.append(types)

next=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div/div/div/div[1]/div/div[4]/li[12]/a')
next.click()

print(len(quote),len(author),len(typs))

200 200 200

In [6]:
lines=driver.find_elements(By.XPATH,'//a[@class="title"]')
for i in lines:
    line=i.text
    quote.append(line)

auth=driver.find_elements(By.XPATH,'//div[@class="author"]')
for i in auth:
    writer=i.text
    author.append(writer)
    
typ=driver.find_elements(By.XPATH,'//div[@class="tags"]')
for i in typ:
    types=i.text
    typs.append(types)

next=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div/div/div/div[1]/div/div[4]/li[12]/a')
next.click()

print(len(quote),len(author),len(typs))

300 300 300

In [7]:
lines=driver.find_elements(By.XPATH,'//a[@class="title"]')
for i in lines:
    line=i.text
    quote.append(line)

auth=driver.find_elements(By.XPATH,'//div[@class="author"]')
for i in auth:
    writer=i.text
    author.append(writer)
    
typ=driver.find_elements(By.XPATH,'//div[@class="tags"]')
for i in typ:
    types=i.text
    typs.append(types)

next=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div/div/div/div[1]/div/div[4]/li[12]/a')
next.click()

print(len(quote),len(author),len(typs))

400 400 400

In [8]:
lines=driver.find_elements(By.XPATH,'//a[@class="title"]')
for i in lines:
    line=i.text
    quote.append(line)

auth=driver.find_elements(By.XPATH,'//div[@class="author"]')
for i in auth:
    writer=i.text
    author.append(writer)
    
typ=driver.find_elements(By.XPATH,'//div[@class="tags"]')
for i in typ:
    types=i.text
    typs.append(types)

next=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div/div/div/div[1]/div/div[4]/li[12]/a')
next.click()

print(len(quote),len(author),len(typs))

500 500 500

In [9]:
lines=driver.find_elements(By.XPATH,'//a[@class="title"]')
for i in lines:
    line=i.text
    quote.append(line)

auth=driver.find_elements(By.XPATH,'//div[@class="author"]')
for i in auth:
    writer=i.text
    author.append(writer)
    
typ=driver.find_elements(By.XPATH,'//div[@class="tags"]')
for i in typ:
    types=i.text
    typs.append(types)

next=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div/div/div/div[1]/div/div[4]/li[12]/a')
next.click()

print(len(quote),len(author),len(typs))

600 600 600

In [10]:
lines=driver.find_elements(By.XPATH,'//a[@class="title"]')
for i in lines:
    line=i.text
    quote.append(line)

auth=driver.find_elements(By.XPATH,'//div[@class="author"]')
for i in auth:
    writer=i.text
    author.append(writer)
    
typ=driver.find_elements(By.XPATH,'//div[@class="tags"]')
for i in typ:
    types=i.text
    typs.append(types)

next=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div/div/div/div[1]/div/div[4]/li[12]/a')
next.click()

print(len(quote),len(author),len(typs))

700 700 700

In [11]:
lines=driver.find_elements(By.XPATH,'//a[@class="title"]')
for i in lines:
    line=i.text
    quote.append(line)

auth=driver.find_elements(By.XPATH,'//div[@class="author"]')
for i in auth:
    writer=i.text
    author.append(writer)
    
typ=driver.find_elements(By.XPATH,'//div[@class="tags"]')
for i in typ:
    types=i.text
    typs.append(types)

next=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div/div/div/div[1]/div/div[4]/li[12]/a')
next.click()

print(len(quote),len(author),len(typs))

800 800 800

In [12]:
lines=driver.find_elements(By.XPATH,'//a[@class="title"]')
for i in lines:
    line=i.text
    quote.append(line)

auth=driver.find_elements(By.XPATH,'//div[@class="author"]')
for i in auth:
    writer=i.text
    author.append(writer)
    
typ=driver.find_elements(By.XPATH,'//div[@class="tags"]')
for i in typ:
    types=i.text
    typs.append(types)

next=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div/div/div/div[1]/div/div[4]/li[12]/a')
next.click()

print(len(quote),len(author),len(typs))

900 900 900

In [13]:
lines=driver.find_elements(By.XPATH,'//a[@class="title"]')
for i in lines:
    line=i.text
    quote.append(line)

auth=driver.find_elements(By.XPATH,'//div[@class="author"]')
for i in auth:
    writer=i.text
    author.append(writer)
    
typ=driver.find_elements(By.XPATH,'//div[@class="tags"]')
for i in typ:
    types=i.text
    typs.append(types)

next=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div/div/div/div[1]/div/div[4]/li[12]/a')
next.click()

print(len(quote),len(author),len(typs))

1000 1000 1000

In [15]:
print(len(quote),len(author),len(typs))

1000 1000 1000

In [16]:
#creating a DataFrame
df=pd.DataFrame({'Quotes':quote,'Author':author,'Type Of Quotes':typs})

In [17]:
df

,Quotes,Author,Type Of Quotes
0,The essence of strategy is choosing what not t...,Michael Porter,"Essence, Deep Thought, Transcendentalism"
1,One cannot and must not try to erase the past ...,Golda Meir,"Inspiration, Past, Trying"
2,Patriotism means to stand by the country. It d...,Theodore Roosevelt,"Country, Peace, War"
3,Death is something inevitable. When a man has ...,Nelson Mandela,"Inspirational, Motivational, Death"
4,You have to love a nation that celebrates its ...,Erma Bombeck,"4th Of July, Food, Patriotic"
...,...,...,...
995,Regret for the things we did can be tempered b...,Sydney J. Harris,"Love, Inspirational, Motivational"
996,America... just a nation of two hundred millio...,Hunter S. Thompson,"Gun, Two, Qualms About"
997,For every disciplined effort there is a multip...,Jim Rohn,"Inspirational, Greatness, Best Effort"
998,"The spiritual journey is individual, highly pe...",Ram Dass,"Spiritual, Truth, Yoga"
999,The mind is not a vessel to be filled but a fi...,Plutarch,"Inspirational, Leadership, Education"

In [2]:
import selenium
import pandas as pd 
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

Q7: Write a python program to display list of respected former Prime Ministers of India (i.e. Name,
Born-Dead, Term of office, Remarks) from https://www.jagranjosh.com/general-knowledge/list-ofall-prime-ministers-of-india-1473165149-1
scrap the mentioned data and make the DataFrame

In [24]:
driver=webdriver.Chrome()
driver.get('https://www.jagranjosh.com/general-knowledge/list-ofall-prime-ministers-of-india-1473165149-1')

In [25]:
#creating empty list
name=[]
born=[]
term_office=[]
remark=[]

In [27]:
table = driver.find_element(By.TAG_NAME, 'table') 
rows = table.find_elements(By.TAG_NAME, 'tr')
data = []

for row in rows:
    cells = row.find_elements(By.TAG_NAME, 'td')  # Get all cells in the row
    row_data = [cell.text for cell in cells]      # Extract text from each cell
    data.append(row_data)            # Append row data to list

In [29]:
df = pd.DataFrame(data)# Convert list to DataFrame for easier handling
df

,0,1,2,3,4,5
0,S.N,Name,Age when assumed office,Term of office,Duration,None
1,1,Jawaharlal Nehru,"57 years, 274 days",15 August1947,27 May 1964,"16 years, 286 days"
2,2,Gulzarilal Nanda,"65 years, 328 days",27 May 1964,9 June 1964,13 days
3,3,Lal Bahadur Shastri,"62 years, 250 days",9 June 1964,11 January 1966,"1 year, 216 days"
4,4,Gulzarilal Nanda,"67 years, 191 days",11 January 1966,24 January 1966,13 days
5,4,Indira Gandhi,"48 years, 66 days",24 January 1966,24 March 1977,"11 years, 59 days"
6,5,Morarji Desai,"81 years, 24 days",24 March 1977,28 July 1979,"2 years, 126 days"
7,6,Charan Singh,"76 years, 217 days",28 July 1979,14 January 1980,170 days
8,7,Indira Gandhi,"62 years, 56 days",14 January 1980,31 October 1984,"4 years, 291 days"
9,8,Rajiv Gandhi,"40 years, 72 days",31 October 1984,2 December 1989,"5 years, 32 days"
10,9,Vishwanath Pratap Singh,"58 years, 160 days",2 December 1989,10 November 1990,343 days
11,10,Chandra Shekhar,"63 years, 207 days",10 November 1990,21 June 1991,223 days
12,11,P. V. Narasimha Rao,"69 years, 358 days",21 June 1991,16 May 1996,"4 years, 330 days"
13,12,Atal Bihari Vajpayee,"71 years, 143 days",16 May 1996,1 June 1996,16 days
14,13,H. D. Deve Gowda,"63 years, 14 days",1 June 1996,21 April 1997,324 days
15,14,Inder Kumar Gujral,"77 years, 138 days",21 April 1997,19 March 1998,332 days
16,15,Atal Bihari Vajpayee,"73 years, 84 days",19 March 1998,22 May 2004,"6 years, 64 days"
17,16,Manmohan Singh,"71 years, 239 days",22 May 2004,26 May 2014,"10 years, 4 days"
18,17,Narendra Modi,"63 years, 251 days",26 May 2014,Incumbent,"10 years, 87 days"

Q8: Write a python program to display list of 50 Most expensive cars in the world
(i.e. Car name and Price) from https://www.motor1.com/
This task will be done in following steps:
1. First get the webpage https://www.motor1.com/
2. Then You have to type in the search bar ’50 most expensive cars’
3. Then click on 50 most expensive carsin the world..
4. Then scrap thementioned data and make the dataframe

In [2]:
driver=webdriver.Chrome()
driver.get('https://www.motor1.com/')

In [3]:
input=driver.find_element(By.XPATH,'/html/body/div[9]/div[2]/div/div/div[3]/div/div/div/form/input')
input.send_keys('50 most expensive cars')
time.sleep(3)

In [4]:
search=driver.find_element(By.XPATH,'/html/body/div[9]/div[2]/div/div/div[3]/div/div/div/form/button[1]')
search.click()
time.sleep(3)

In [5]:
press=driver.find_element(By.XPATH,'/html/body/div[9]/div[9]/div/div[1]/div/div/div[1]/div/div[1]/h3/a')
press.click()
time.sleep(3)

In [7]:
#creating empty list
car_name=[]
car_price=[]

In [8]:
name=driver.find_elements(By.XPATH,'//h3[@class="subheader"]')
for i in name[0:50]:
    title=i.text
    car_name.append(title)

In [9]:
#we are using //p/strong because their is no class of p tag and we have to scrap the data
price=driver.find_elements(By.XPATH,'//p/strong')
for i in price:
    money=i.text
    car_price.append(money)

In [11]:
print(len(car_name),len(car_price))

50 50

In [12]:
#creating a DataFrame
df=pd.DataFrame({'Cars':car_name,'Price':car_price})
df

                                         Cars                        Price
0                           McLaren Senna GTR                 $1.7 Million
1                                 Czinger 21C          Price: $1.7 Million
2                               Ferrari Monza          Price: $1.7 Million
3                          Gordon Murray T.33          Price: $1.7 Million
4                           Koenigsegg Gemera          Price: $1.7 Million
5                          Hennessey Venom F5          Price: $1.8 Million
6                             Bentley Bacalar          Price: $1.9 Million
7               Hispano Suiza Carmen Boulogne          Price: $1.9 Million
8                      Bentley Mulliner Batur          Price: $2.0 Million
9                                 SSC Tuatara          Price: $2.0 Million
10                                Lotus Evija          Price: $2.1 Million
11                        Aston Martin Vulcan          Price: $2.3 Million
12                                 Delage D12          Price: $2.3 Million
13                        Ferrari Daytona SP3          Price: $2.3 Million
14                          McLaren Speedtail          Price: $2.3 Million
15                               Rimac Nevera          Price: $2.4 Million
16                              Pagani Utopia          Price: $2.5 Million
17                       Pininfarina Battista          Price: $2.5 Million
18                         Gordon Murray T.50          Price: $2.6 Million
19                       Lamborghini Countach          Price: $2.6 Million
20              Hennessey Venom F5 Revolution                 $2.7 Million
21                   Mercedes-AMG Project One          Price: $2.7 Million
22                               Zenvo Aurora          Price: $2.8 Million
23                        Aston Martin Victor          Price: $3.0 Million
24                Hennessey Venom F5 Roadster                 $3.0 Million
25                           Koenigsegg Jesko          Price: $3.0 Million
26                                 Aspark Owl                 $3.1 Million
27                      Aston Martin Valkyrie          Price: $3.2 Million
28                  W Motors Lykan Hypersport          Price: $3.4 Million
29                              McLaren Solus                 $3.5 Million
30                        Pagani Huayra Evo R          $3.5 Million (est.)
31                           Lamborghini Sian          Price: $3.6 million
32                           Koenigsegg CC850          Price: $3.7 Million
33            Bugatti Chiron Super Sport 300+          Price: $3.9 Million
34  Gordon Murray Automotive T.50s Niki Lauda                 $3.9 Million
35                  Pagani Huayra Roadster BC                 $4.0 Million
36                         Lamborghini Veneno          Price: $4.5 Million
37                             Bugatti Bolide          Price: $4.7 Million
38                  Pininfarina B95 Speedster          Price: $4.8 Million
39                            Bugatti Mistral          Price: $5.0 Million
40                               Bugatti Divo          Price: $5.8 Million
41                        Pagani Huayra Imola                 $6.0 Million
42                           Pagani Codalunga          Price: $7.4 Million
43                   Mercedes-Maybach Exelero          Price: $8.0 Million
44                         Bugatti Centodieci          Price: $9.0 Million
45                    Bugatti Chiron Profilée         Price: $10.8 Million
46                       Rolls-Royce Sweptail         Price: $12.8 Million
47                   Bugatti La Voiture Noire         Price: $13.4 Million
48                      Rolls-Royce Boat Tail  Price: $28.0 Million (est.)
49         Rolls-Royce La Rose Noire Droptail    Price: $30 Million (est.)